[phases.setup]
nixPkgs = [
  "nodejs_18",
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "libxcb",
  "libxkbcommon",
  "mesa",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxshmfence",
  "xorg.libXtst",
  "alsa-lib"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
